

//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace RegAndAuth
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class SignUpandInEntities : DbContext
{
    public SignUpandInEntities()
        : base("name=SignUpandInEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Product> Product { get; set; }

    public virtual DbSet<Tasks> Tasks { get; set; }

    public virtual DbSet<UserRole> UserRole { get; set; }

    public virtual DbSet<Users> Users { get; set; }

}

}

